from _typeshed import Incomplete
from collections.abc import Generator
from datalad_core.config import get_manager as get_manager
from datalad_core.runners import call_git as call_git, call_git_lines as call_git_lines
from datalad_core.tests.utils import modify_dataset as modify_dataset
from pathlib import Path as Path

magic_marker: str
standard_gitconfig: Incomplete

def cfgman(monkeypatch) -> Generator[Incomplete, None, None]: ...
def verify_pristine_gitconfig_global() -> Generator[None, None, Incomplete]: ...
def gitrepo(tmp_path_factory) -> Generator[Path]: ...
def baregitrepo(tmp_path_factory) -> Generator[Path]: ...
def bareannexrepo(baregitrepo) -> Generator[Path]: ...
def annexrepo(gitrepo) -> Generator[Path]: ...
def symlinks_supported(tmp_path_factory) -> bool: ...
def skip_when_symlinks_not_supported(symlinks_supported) -> None: ...
def modified_dataset(tmp_path_factory) -> Generator[Incomplete, None, None]: ...
