from .. import utils as utils
from ..utils import get_gitconfig_items_from_env as get_gitconfig_items_from_env, set_gitconfig_items_in_env as set_gitconfig_items_in_env

def test_get_gitconfig_items_from_env(monkeypatch) -> None: ...
def test_set_gitconfig_items_in_env(monkeypatch) -> None: ...
def test_get_set_gitconfig_env_roundtrip(monkeypatch) -> None: ...
