from ..gitenv import GitEnvironment as GitEnvironment
from datalad_core.runners import call_git_lines as call_git_lines, call_git_oneline as call_git_oneline

def test_gitenv_singlevalue() -> None: ...
def test_gitenv_multivalue() -> None: ...
