from annexremote import RemoteError as _RemoteError
from annexremote import SpecialRemote as _SpecialRemote

__all__ = ['RemoteError', 'SpecialRemote']

class RemoteError(_RemoteError): ...

class SpecialRemote(_SpecialRemote):
    def __init__(self, annex) -> None: ...
    def message(self, msg, type: str = 'debug') -> None: ...
    def send_progress(self, progress) -> None: ...
