from _typeshed import Incomplete

__docformat__: str
logger: Incomplete

class LineSplitter:
    separator: Incomplete
    keep_ends: Incomplete
    remaining_data: Incomplete
    def __init__(self, separator: str | None = None, keep_ends: bool = False) -> None: ...
    def process(self, data: str) -> list[str]: ...
    def finish_processing(self) -> str | None: ...

class AssemblingDecoderMixIn:
    remaining_data: Incomplete
    def __init__(self) -> None: ...
    def decode(self, fd: int, data: bytes, encoding: str) -> str: ...
    def __del__(self) -> None: ...
