from datasalad.settings import Defaults

class ImplementationDefaults(Defaults): ...

def get_defaults() -> ImplementationDefaults: ...
def register_defaults_gitcfg(defaults: ImplementationDefaults) -> None: ...
def anything2bool(val): ...
